version: 0.0
os:
  - linux
files:
  - source: /
    destination: /home/juulabel-front
file_exists_behavior: OVERWRITE
permissions:
  - object: /home/juulabel-front
    pattern: "**"
    owner: root
    group: root
    mode: 755
hooks:
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: root
