name: "Update Document"
title: "DOCS: "
labels: ["[DOCS]"]

description: |
  문서 업데이트 혹은 작성
body:
  - type: textarea
    attributes:
      label: 어떤 문서인가요?
      description: 업데이트하거나 작성하려는 문서에 대해 간결하게 설명해주세요.
    validations:
      required: true
  - type: textarea
    attributes:
      label: 작업 상세 내용
      description: .
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: 참고할만한 자료
      description: 참고할만한 자료 및 파일을 첨부해주세요
